version: '3.8'

services:
  zoom-app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: zoom-service:latest
    ports:
      - "8808:80"
    environment:
      # Zoom API配置 - 请在.env文件中设置或通过环境变量传入
      # - ZOOM_API_KEY=${ZOOM_API_KEY}
      # - ZOOM_API_SECRET=${ZOOM_API_SECRET}
      - ZOOM_ACCOUNT_ID=${ZOOM_ACCOUNT_ID}
      - ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
      - ZOOM_CLIENT_SECRET=${ZOOM_CLIENT_SECRET}
      # 功能开关
      - DISABLE_JOIN_MEETING=true
      - DISABLE_DOOTASK_AUTH=true
    volumes:
      # 可选：挂载日志目录
      - ./logs:/var/log/supervisor
    restart: unless-stopped